!function(t,e){"use strict";var i="mayar";if(!e.getElementById(i)){var n=e.getElementsByTagName("head")[0],o=e.createElement("link");o.id=i,o.rel="stylesheet",o.type="text/css",o.href="https://raw.githack.com/javabitpro/buttoncssbeli/main/buttonbeli-min.css",o.media="all",n.appendChild(o)}var s=e.body||"",l="appendChild",a="classList",d="createElement",r="dataset",c="getElementsByClassName",h="addEventListener",f="iframe-lightbox",m="iframe-lightbox--open",u="iframe-lightbox-link--is-binded",p="is-loaded",b="is-opened",y="is-showing",g=function(t,i){var n=i||{};this.trigger=t,this.el=e[c](f)[0]||"",this.body=this.el?this.el[c]("body")[0]:"",this.content=this.el?this.el[c]("content")[0]:"",this.src=t[r].src||"",this.href=t.getAttribute("href")||"",this.dataPaddingBottom=t[r].paddingBottom||"",this.dataScrolling=t[r].scrolling||"",this.rate=n.rate||500,this.scrolling=n.scrolling,
/*!
         * Event handlers
         */
this.onOpened=n.onOpened,this.onIframeLoaded=n.onIframeLoaded,this.onLoaded=n.onLoaded,this.onCreated=n.onCreated,this.onClosed=n.onClosed,this.init()};g.prototype.init=function(){var t=this;this.el||this.create();var e=function(){t.open()};this.trigger[a].contains(u)||(this.trigger[a].add(u),this.trigger[h]("click",(function(t){var i,n,o,s,l,a;t.stopPropagation(),t.preventDefault(),(i=e,n=this.rate,function(){l=this,s=[].slice.call(arguments,0),a=new Date;var t=function(){var e=new Date-a;e<n?o=setTimeout(t,n-e):(o=null,i.apply(l,s))};o||(o=setTimeout(t,n))}).call()})))},g.prototype.create=function(){var i=this,n=e[d]("div");this.el=e[d]("div"),this.content=e[d]("div"),this.body=e[d]("div"),this.el[a].add(f),n[a].add("backdrop"),this.content[a].add("content"),this.body[a].add("body"),this.el[l](n),this.content[l](this.body),this.contentHolder=e[d]("div"),this.contentHolder[a].add("content-holder"),this.contentHolder[l](this.content),this.el[l](this.contentHolder),this.btnClose=e[d]("a"),this.btnClose[a].add("btn-close"),this.btnClose.setAttribute("href","javascript:void(0);"),this.el[l](this.btnClose),s[l](this.el),n[h]("click",(function(){i.close()})),this.btnClose[h]("click",(function(){i.close()})),t[h]("keyup",(function(t){27===(t.which||t.keyCode)&&i.close()}));var o=function(){i.isOpen()||(i.el[a].remove(y),i.body.innerHTML="")};this.el[h]("transitionend",o,!1),this.el[h]("webkitTransitionEnd",o,!1),this.el[h]("mozTransitionEnd",o,!1),this.el[h]("msTransitionEnd",o,!1),this.callCallback(this.onCreated,this)},g.prototype.loadIframe=function(){var t=this;this.iframeId=f+Date.now(),this.iframeSrc=this.src||this.href||"";
/*!
         * @see {@link https://stackoverflow.com/questions/18648203/how-remove-horizontal-scroll-bar-for-iframe-on-google-chrome}
         */
var i,n,o,s=[];s.push('<iframe src="'+this.iframeSrc+'" name="'+this.iframeId+'" id="'+this.iframeId+'" onload="this.style.opacity=1;" style="opacity:0;border:none;" webkitallowfullscreen="true" mozallowfullscreen="true" allowfullscreen="true" height="166" frameborder="no"></iframe>'),
/*!
         * @see {@link https://epic-spinners.epicmax.co/}
         */
s.push('<div class="half-circle-spinner"><div class="circle circle-1"></div><div class="circle circle-2"></div></div>'),this.body.innerHTML=s.join(""),i=this.iframeId,n=this.body,(o=e.getElementById(i)).onload=function(){this.style.opacity=1,n[a].add(p),t.scrolling||t.dataScrolling?(o.removeAttribute("scrolling"),o.style.overflow="scroll"):(o.setAttribute("scrolling","no"),o.style.overflow="hidden"),t.callCallback(t.onIframeLoaded,t),t.callCallback(t.onLoaded,t)}},g.prototype.open=function(){this.loadIframe(),this.dataPaddingBottom?this.content.style.paddingBottom=this.dataPaddingBottom:this.content.removeAttribute("style"),this.el[a].add(y),this.el[a].add(b),s[a].add(m),this.callCallback(this.onOpened,this)},g.prototype.close=function(){this.el[a].remove(b),this.body[a].remove(p),s[a].remove(m),this.callCallback(this.onClosed,this)},g.prototype.isOpen=function(){return this.el[a].contains(b)},g.prototype.callCallback=function(t,e){"function"==typeof t&&t.bind(this)(e)},t.IframeLightbox=g}("undefined"!=typeof window?window:this,document),function(t,e){"use strict";[].forEach.call(e.getElementsByClassName("iframe-lightbox-link"),(function(t){t.lightbox=new IframeLightbox(t,{onCreated:function(){},onLoaded:function(){},onError:function(){},onClosed:function(){},scrolling:!1,rate:500})}))}("undefined"!=typeof window&&window,document);
